In [18]:
#Write a function so that the columns of the output matrix are powers of the input vector.
#The order of the powers is determined by the increasing boolean argument. Specifically, when
#increasing is False, the i-th output column is the input vector raised element-wise to the power
#of N - i - 1.

In [24]:
import numpy as np
def vander_func(vector,n,increasing = False):
    x = np.array(vector)
    if not increasing:
        new_array = np.column_stack([x**(n-i-1) for i in range(n)])
    if increasing :
        new_array = np.column_stack([x**i for i in range(n)])
    return new_array

In [25]:
vander_func([1,2,3,4,5],5,True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]], dtype=int32)

In [26]:
vander_func([1,2,3,4,5],5,False)


array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]], dtype=int32)

In [ ]:
##Write a function to find moving average in an array over a window:
#Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [ ]:
import numpy as np

In [11]:
import numpy as np
dataset = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
def M_av(ds,w):
    a = np.cumsum(b)
    #this will give us cumulative sum ,  but as per desired in question we have to keep sum of next 3 numbers, 
    # so we have to subtract the carried total from numbers before 3rd number,
    a[w:] = a[w:] - a[:-w]
    return a[w-1:]/w # to include first 3 sum as well we have to take range from w-1.;


In [12]:
M_av(dataset,3).round(2)

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])