In [18]:
#Write a function so that the columns of the output matrix are powers of the input vector.
#The order of the powers is determined by the increasing boolean argument. Specifically, when
#increasing is False, the i-th output column is the input vector raised element-wise to the power
#of N - i - 1.

In [24]:
import numpy as np
def vander_func(vector,n,increasing = False):
    x = np.array(vector)
    if not increasing:
        new_array = np.column_stack([x**(n-i-1) for i in range(n)])
    if increasing :
        new_array = np.column_stack([x**i for i in range(n)])
    return new_array

In [25]:
vander_func([1,2,3,4,5],5,True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]], dtype=int32)

In [26]:
vander_func([1,2,3,4,5],5,False)


array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]], dtype=int32)

In [ ]:
##Write a function to find moving average in an array over a window:
#Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [ ]:
import numpy as np

In [12]:
dataset = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
def movingaverage(data,window):
    w = np.repeat(1.0 , window)/window
    M_av = np.convolve(data,w,'valid')
    return M_av
movingaverage(dataset,3)


array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])